# render.yaml
services:
  - type: web
    name: user_management
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import os; print('BUILD: Current dir:', os.getcwd()); print('BUILD: Files:', os.listdir('.'))"
    startCommand: python -c "import os, sys; print('START: Current dir:', os.getcwd()); print('START: Files:', os.listdir('.')); sys.exit(1)"